In [18]:
import numpy as np
from numpy.random import randint #importing random integer generating fun from numpy.random

arr1=np.random.randint(1,50,(3,2)) #this will create a 3*2 matrix with random no in between 1-50
arr2=np.random.randint(1,50,(6,7)) #this will create a 6*7 matrix with random no in between 1-50

np.save("array1",arr1)
np.save("array2",arr2)


[[33  9]
 [30  9]
 [19 13]]

 [[ 4  4 32 49 43 43 33]
 [10  7 44 17 14 45 22]
 [24 36 40 19 35 35 37]
 [29  3 40  7  7 49 35]
 [43  3 27 48 24 48 30]
 [12 44 13 35 36 42 36]]
